# Generated by Django 5.2.1 on 2025-06-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
    ]
