# Generated by Django 5.2.1 on 2025-06-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_usuario_is_staff_alter_usuario_is_superuser'),
    ]

    operations = [
    ]
