# Generated by Django 5.2.1 on 2025-06-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_auto_20250602_1337'),
    ]

    operations = [
    ]
