# Generated by Django 5.2.1 on 2025-06-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0008_auto_20250602_1340'),
    ]

    operations = [
    ]
