# Generated by Django 5.2.1 on 2025-06-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0010_auto_20250602_1346'),
    ]

    operations = [
    ]
