# Generated by Django 5.2.1 on 2025-06-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0013_auto_20250602_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='opciones_menu',
            field=models.ManyToManyField(blank=True, to='mi_app.opcionmenu'),
        ),
    ]
