# Generated by Django 5.2.1 on 2025-06-20 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0015_estado_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.IntegerField(primary_key=True, serialize=False)),
                ('region_code', models.CharField(max_length=10)),
                ('region_name', models.CharField(max_length=25)),
                ('show_ind', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='opcionmenu',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='mi_app.opcionmenu'),
        ),
        migrations.AlterField(
            model_name='opcionmenu',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opcionmenu',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
