# Generated by Django 5.2.1 on 2025-06-23 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0016_region_alter_ciudad_options_alter_estado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='opcionmenu',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='menus_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opcionmenu',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudad',
        ),
        migrations.AlterModelTable(
            name='estado',
            table='state',
        ),
    ]
