# Generated by Django 5.2.1 on 2025-06-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0017_alter_usuario_managers_opcionmenu_usuarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='archivos_clientes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='opciones_menu',
            field=models.ManyToManyField(blank=True, related_name='usuarios_asignados', to='mi_app.opcionmenu'),
        ),
    ]
